apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
      - name: init-mysql-config
        image: busybox
        command:
        - sh
        - -c
        - |
          cp /mnt/config/my.cnf /mnt/tmp/my-tmp.cnf;
          server_id=$(($(echo ${MYSQL_HOSTNAME##*-} | tr -d '[:alpha:]') + 1));
          echo "server-id=${server_id}" >> /mnt/tmp/my-tmp.cnf;
          echo "loose-group_replication_local_address=${MYSQL_HOSTNAME}.mysql:33061" >> /mnt/tmp/my-tmp.cnf;
          cp /mnt/tmp/my-tmp.cnf /mnt/config/my.cnf;
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config
        - name: tmp-volume
          mountPath: /mnt/tmp
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
           secretKeyRef:
            key: ROOT_PASSWORD
            name: mysecret
        - name: MYSQL_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: config-volume
          mountPath: /etc/mysql/conf.d
          subPath: my.cnf
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 10Gi
      storageClassName: "nfs-client"
  volumes:
  - name: config-volume
    configMap:
      name: mysql-config
  - name: tmp-volume
    emptyDir: {}
