apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    server_id=1
    log-bin=mysql-bin
    binlog_format=row
    gtid_mode=ON
    enforce_gtid_consistency=ON
    master-info-repository=TABLE
    relay-log-info-repository=TABLE
    log-slave-updates=ON
    transaction-write-set-extraction=XXHASH64
    loose-group_replication_bootstrap_group=OFF
    loose-group_replication_group_name="889f3753-22e5-436e-b9fd-db3475fdec59"
    loose-group_replication_start_on_boot=off
    loose-group_replication_local_address="mysql-0.mysql:33061"
    loose-group_replication_ip_allowlist="mysql-0.mysql,mysql-1.mysql,mysql-2.mysql"
    loose-group_replication_group_seeds="mysql-0.mysql:33061,mysql-1.mysql:33061,mysql-2.mysql:33061"
    loose-group_replication_single_primary_mode=off
    loose-group_replication_enforce_update_everywhere_checks=ON
    bind-address="0.0.0.0"
    report-hosts="mysq-0.mysql"
