apiVersion: v1
kind: Service
metadata:
  name: db-sipso-service
spec:
  selector:
    app: dbipso
  ports:
    - port: 3306
      targetPort: 3306
  type: LoadBalancer

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-sipso
spec:
  serviceName: "db-sipso-service"
  replicas: 2
  selector:
    matchLabels:
      app: dbipso
  template:
    metadata:
      labels:
        app: dbipso
    spec:
      containers:
      - name: dbipso
        image: mysql:5.6
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-pv
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500M
